In [2]:
import numpy as np
import pandas as pd

In [3]:
df_sus2020 = pd.read_csv('esus-vepi.LeitoOcupacao_2020.csv')

C:\Users\lharm\AppData\Local\Temp\ipykernel_21004\2840732344.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sus2020 = pd.read_csv('esus-vepi.LeitoOcupacao_2020.csv')

In [5]:
df_sus2020.head(5)

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,...,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,validado,_created_at,_updated_at
0,0,p5Ez41Zu6B,2020-04-14T03:00:00.000Z,2303167,0.0,0.0,0.0,0.0,NaN,NaN,...,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,False,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z
1,1,eUOMsSt7T7,2020-04-15T03:00:00.000Z,5935377\t,1.0,0.0,0.0,0.0,NaN,NaN,...,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z
2,2,QaG4oIBrMa,2020-04-15T14:57:16.255Z,0012599,15.0,1.0,3.0,2.0,NaN,NaN,...,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z
3,3,ifya31F3ZF,2020-03-24T03:00:00.000Z,2562871,9.0,0.0,1.0,0.0,NaN,NaN,...,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z
4,4,dkurDhelx9,2020-04-01T03:00:00.000Z,2252228,26.0,0.0,1.0,0.0,NaN,NaN,...,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z

In [8]:
df_sus2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 554693 entries, 0 to 554692
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             554693 non-null  int64
 1   _id                    554693 non-null  object
 2   dataNotificacao        554693 non-null  object
 3   cnes                   554643 non-null  object
 4   ocupacaoSuspeitoCli    554286 non-null  float64
 5   ocupacaoSuspeitoUti    554286 non-null  float64
 6   ocupacaoConfirmadoCli  554287 non-null  float64
 7   ocupacaoConfirmadoUti  554287 non-null  float64
 8   ocupacaoCovidUti       517 non-null     float64
 9   ocupacaoCovidCli       517 non-null     float64
 10  ocupacaoHospitalarUti  517 non-null     float64
 11  ocupacaoHospitalarCli  517 non-null     float64
 12  saidaSuspeitaObitos    554577 non-null  float64
 13  saidaSuspeitaAltas     554589 non-null  float64
 14  saidaConfirmadaObitos  554681 non-null  float64
 15  saidaConfirmadaAltas   554680 non-null  float64
 16  origem                 554693 non-null  object
 17  _p_usuario             554693 non-null  object
 18  estadoNotificacao      554693 non-null  object
 19  municipioNotificacao   554693 non-null  object
 20  estado                 554692 non-null  object
 21  municipio              554692 non-null  object
 22  excluido               554693 non-null  bool
 23  validado               554693 non-null  bool
 24  _created_at            554693 non-null  object
 25  _updated_at            554693 non-null  object
dtypes: bool(2), float64(12), int64(1), object(11)
memory usage: 102.6+ MB

In [9]:
df_sus2020.describe().round(1)

,Unnamed: 0,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas
count,554693.0,554286.0,554286.0,554287.0,554287.0,517.0,517.0,517.0,517.0,554577.0,554589.0,554681.0,554680.0
mean,280224.4,190.1,7.1,6.1,4.5,5.2,4.6,7.1,22.1,0.2,51.4,0.4,34.0
std,167798.1,62088.1,16.1,33.2,11.3,8.6,5.8,12.3,51.0,3.6,37668.5,3.7,17293.0
min,0.0,-57.0,-9.0,-10.0,-7.0,-1.0,0.0,0.0,0.0,-10.0,-12.0,-3.0,-13.0
25%,138706.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,277388.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,8.0,0.0,0.0,0.0,0.0
75%,416084.0,27.0,8.0,6.0,5.0,17.0,10.0,20.0,11.0,0.0,0.0,0.0,0.0
max,1642819.0,29082020.0,924.0,22222.0,334.0,44.0,60.0,195.0,314.0,425.0,28052020.0,322.0,9112020.0

In [39]:
df_cancer = pd.read_csv('Cancer_Data.csv')

In [40]:
# df_cancer.[df_cancer['diagnosis'] == 'B']

df_cancer.loc[df_cancer['diagnosis'] == 'B', 'id'].count()

357

In [46]:
df_cancer['diagnosis'] = df_cancer['diagnosis'].str.replace('B', 'benign cancer').replace('M', 'malignant cancer')
df_cancer['diagnosis'].value_counts()

diagnosis
benign cancer       357
malignant cancer    212
Name: count, dtype: int64

In [47]:
df_cancer.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,malignant cancer,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,malignant cancer,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,malignant cancer,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,malignant cancer,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,malignant cancer,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [56]:
df_cancer[(df_cancer['diagnosis']=='malignant cancer')&(df_cancer['radius_mean']>25)]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
82,8611555,malignant cancer,25.22,24.91,171.5,1878.0,0.1063,0.2665,0.3339,0.1845,...,33.62,211.7,2562.0,0.1573,0.6076,0.6476,0.2867,0.2355,0.10510,NaN
180,873592,malignant cancer,27.22,21.87,182.1,2250.0,0.1094,0.1914,0.2871,0.1878,...,32.85,220.8,3216.0,0.1472,0.4034,0.5340,0.2688,0.2856,0.08082,NaN
212,8810703,malignant cancer,28.11,18.47,188.5,2499.0,0.1142,0.1516,0.3201,0.1595,...,18.47,188.5,2499.0,0.1142,0.1516,0.3201,0.1595,0.1648,0.05525,NaN
352,899987,malignant cancer,25.73,17.46,174.2,2010.0,0.1149,0.2363,0.3368,0.1913,...,23.58,229.3,3234.0,0.1530,0.5937,0.6451,0.2756,0.3690,0.08815,NaN
461,911296202,malignant cancer,27.42,26.27,186.9,2501.0,0.1084,0.1988,0.3635,0.1689,...,31.37,251.2,4254.0,0.1357,0.4256,0.6833,0.2625,0.2641,0.07427,NaN